name: Backwards Compatibility Tests k-NN
on:
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"

jobs:
  Restart-Upgrade-BWCTests-k-NN:
    strategy:
      matrix:
        java: [11, 17]
        bwc_versions_restart_upgrade : [ "1.0.0", "1.1.0", "1.2.4", "1.3.1" ]
        latest_version_restart_upgrade : [ "2.0.0-rc1-SNAPSHOT" ]

    name: k-NN Restart-Upgrade BWC Tests
    runs-on: ubuntu-latest
    env:
      BWC_VERSION_RESTART_UPGRADE: ${{ matrix.bwc_versions_restart_upgrade }}

    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: |
          sudo apt-get install libopenblas-dev gfortran -y


      - name: Run k-NN Restart-Upgrade BWC Tests from BWCVersion-${{ matrix.bwc_versions_restart_upgrade }} to latest version-${{ matrix.latest_version_restart_upgrade }}
        run: |
          echo "Running restart-upgrade backwards compatibility tests ..."
          ./gradlew :qa:restart-upgrade:testRestartUpgrade -Dtests.bwc.version=$BWC_VERSION_RESTART_UPGRADE


  Rolling-Upgrade-BWCTests-k-NN:
    strategy:
      matrix:
        java: [ 11, 17 ]
        bwc_version_rolling_upgrade: [ "1.3.1" ]
        latest_version_rolling_upgrade: [ "2.0.0-rc1-SNAPSHOT" ]

    name: k-NN Rolling-Upgrade BWC Tests
    runs-on: ubuntu-latest
    env:
      OPENSEARCH_VERSION_ROLLING_UPGRADE: ${{ matrix.latest_version_rolling_upgrade }}

    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: |
          sudo apt-get install libopenblas-dev gfortran -y

      - name: Run k-NN Rolling-Upgrade BWC Tests from BWCVersion-${{ matrix.bwc_version_rolling_upgrade }} to latest version-${{ matrix.latest_version_rolling_upgrade }}
        run: |
          echo "Running rolling-upgrade backwards compatibility tests ..."
          ./gradlew :qa:rolling-upgrade:testRollingUpgrade -Drolling.bwctests.opensearch.version=$OPENSEARCH_VERSION_ROLLING_UPGRADE

